name: offline_upi_tracker
description: A Flutter app to track UPI transactions offline
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.4.0
  local_auth: ^2.2.6
  path_provider: ^2.0.15
  csv: 5.0.0
  flutter_notification_listener: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo/gpay.png
    - assets/logo/phonepe.png
    - assets/logo/paytm.png
    - assets/logo/amazonpay.png
    - assets/logo/bhim.png
    - assets/logo/sbi.png
    - assets/logo/hdfc.png
    - assets/logo/icici.png
    - assets/logo/bob.png
    - assets/logo/kotak.png

flutter_icons:
  android: true
  ios: false
  image_path: assets/logo.png
