name: expense_tracker
description: A Flutter app to track UPI & expenses with notification listener
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0

  # ✅ Recommended maintained package (safe for GitHub Actions)
  flutter_notification_listener2: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
