name: upi_tracker
description: Offline UPI Tracker with Hive, Biometric Lock, CSV Export
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  flutter_notification_listener: ^1.3.4
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png   # Splash screen + Drawer
    - assets/logo/      # GPay, PhonePe, Paytm, etc.
