name: offline_upi_tracker
description: A Flutter app to track UPI transactions offline.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.5   # ✅ compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1   # ✅ added for icon generation

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

# Flutter launcher icon setup
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
