name: expense_tracker
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0

  # ✅ Fixed forked plugin (V2 embedding supported)
  flutter_notification_listener:
    git:
      url: https://github.com/juliansteenbakker/flutter_notification_listener
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
