name: expense_tracker
description: A Flutter Expense Tracker with Notification Listener & Hive Storage
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Hive (local database)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Notification listener (patched for Android embedding v2)
  flutter_notification_listener:
    git:
      url: https://github.com/juliansteenbakker/flutter_notification_listener.git
      ref: master

  # State management
  provider: ^6.1.2

  # UI / Utils
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
